### ISSUE TITLE
Plugin not starting on 1.20.4

### ISSUE THREAD

**Issue by DarkyG2** [Folia-Inquisitors/MoreFoWorld#6]
Here is the error I'm getting in 1.20.4 after updating from 1.5.1 to 1.7.1
```
[19:38:57] [Server thread/ERROR]: Error occurred while enabling MoreFoWorld v1.7.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/core/RegistryAccess
	at me.hsgamer.morefoworld.MoreFoWorld.enable(MoreFoWorld.java:45) ~[MoreFoWorld-1.7.1-all.jar:?]
	at me.hsgamer.morefoworld.minelib.plugin.base.BasePlugin.onEnable(BasePlugin.java:78) ~[MoreFoWorld-1.7.1-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[luminol-1.20.4.jar:git-Luminol-"5579f65"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[luminol-1.20.4.jar:git-Luminol-"5579f65"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:646) ~[luminol-1.20.4.jar:git-Luminol-"5579f65"]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:557) ~[luminol-1.20.4.jar:git-Luminol-"5579f65"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:277) ~[luminol-1.20.4.jar:git-Luminol-"5579f65"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[luminol-1.20.4.jar:git-Luminol-"5579f65"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[luminol-1.20.4.jar:git-Luminol-"5579f65"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.core.RegistryAccess
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:142) ~[luminol-1.20.4.jar:git-Luminol-"5579f65"]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[luminol-1.20.4.jar:git-Luminol-"5579f65"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 12 more
[19:38:57] [Server thread/INFO]: [MoreFoWorld] Disabling MoreFoWorld v1.7.1
```

**Comment by HSGamer** [comment]
Latest version only works on 1.21.1

**Comment by DarkyG2** [comment]
> Latest version only works on 1.21.1

Is it possible to backport it to 1.20.4 ? Folia 1.21.1 is highly unstable

**Comment by HSGamer** [comment]
> > Latest version only works on 1.21.1
> 
> Is it possible to backport it to 1.20.4 ? Folia 1.21.1 is highly unstable

No. You should download the version that supports 1.20.4
We don't backport in latest version
